### ISSUE TITLE
new to python-tutum seeing error on console

### ISSUE THREAD

**Issue by rajpant** [tutumcloud/python-tutum#21]
Hi There,

I have installed python-tutum.

I have written a file test-tutum.py:
import tutum

tutum.user = myuser(my tutum user name)
tutum.apikey = mykey(my api key from tutum)

actions = tutum.Action.list()
print actions;

if i run this file using python test-tutum.py it shows me eorrs:
File "/home/developer/.local/lib/python2.7/site-packages/tutum/__init__.py", line 7, in <module>
    install_aliases()
  File "/home/developer/.local/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "/home/developer/Desktop/python/tutum/test.py", line 24, in <module>
    actions = tutum.Action.list()
AttributeError: 'module' object has no attribute 'Action'

Could you please help me out. 
Thanks in advance!

**Comment by tifayuki** [comment]
which version of python-tutum are you using?
It works fin on the latest version:
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tutum
>>> tutum.__version__
'0.21.1'
>>> actions = tutum.Action.list()
>>> len(actions)
171```

**Comment by rajpant** [comment]
Hi 
please find the version below:
>>> import tutum
>>> tutum.__version__
'0.21.1'
>>> tutum.Service.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tutum/api/base.py", line 143, in list
    json = send_request('GET', endpoint, params=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tutum/api/http.py", line 50, in send_request

**Comment by tifayuki** [comment]
I think it has something to do with the pip dependencies.
Below is what is installed on my virtualenv:
```
(cli)➜  ~  pip freeze
ago==0.0.6
backports.ssl-match-hostname==3.4.0.2
docker-py==1.2.3
future==0.15.0
python-dateutil==2.4.2
python-tutum==0.21.1
PyYAML==3.10
requests==2.7.0
six==1.9.0
tabulate==0.7.2
tutum==0.21.1
websocket-client==0.32.0
wheel==0.24.0
```
Can you try if it works in a clean environment, like virtualenv?

**Comment by rajpant** [comment]
Hi, 
I have installed all the dependencies but it show me following errors even after specifying correct tutum.user and tutum.apikey: 

  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tutum/api/base.py", line 143, in list
    json = send_request('GET', endpoint, params=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tutum/api/http.py", line 50, in send_request
    raise TutumAuthError("Not authorized")
tutum.api.exceptions.TutumAuthError: Not authorized

**Comment by tifayuki** [comment]
@rajpant  I have published a new version `0.21.2`, which fixed the issue.
Sorry for the inconvenience.

**Comment by rajpant** [comment]
@tifayuki  after updating the package it working on terminal. if I write the same command in a py file and try to run is on terminal using python command it shows me errors:
File "/home/developer/Desktop/python/test.py", line 9, in <module>
    tutum.Service.list()
AttributeError: 'module' object has no attribute 'Service'
